### ISSUE TITLE
`DecodeStream` lacks support for many `custom_x_flag` sequence header fields

### ISSUE THREAD

**Issue by mossblaser** [bbc/vc2-reference#12]
Many of these overrides are not supported (despite generally being purely
metadata and not requiring any special decoder behaviour). The following test
bitstreams exercise all permissible settings of these flags.

[custom_flags.zip](https://github.com/bbc/vc2-reference/files/4823996/custom_flags.zip)

```
$ DecodeStream custom_flags_1.vc2 out.16p2
$ DecodeStream custom_flags_2.vc2 out.16p2
Error: DataUnitIO: custom_pixel_aspect_ratio_flag set, shouldn't be
$ DecodeStream custom_flags_3.vc2 out.16p2
Error: DataUnitIO: Invalid Frame Rate on Input: 0
$ DecodeStream custom_flags_4.vc2 out.16p2
Error: DataUnitIO: Invalid Frame Rate on Input: 0
```

NB: The first test file sets all custom flags to false (and is correctly decoded by the decoder). The remaining test files encode exactly the same video format but set some or all custom value flags.

**Comment by GalenReich** [comment]
### All the 'custom_*' parameters in the spec
- [ ] custom_clean_area_flag
- [ ] custom_color_diff_format_flag
- [ ] custom_color_spec_flag
- [ ] custom_color_primaries_flag
- [ ] custom_color_matrix_flag
- [ ] custom_dimensions_flag
- [ ] custom_frame_rate_flag
- [ ] custom_pixel_aspect_ratio_flag
- [ ] custom_scan_format_flag
- [ ] custom_signal_range_flag
- [ ] custom_transfer_fuction_flag
