### ISSUE TITLE
`Encode*` does not specify appropriate clean area

### ISSUE THREAD

**Issue by mossblaser** [bbc/vc2-reference#16]
The various `Encode*` commands fail to specify a clean area appropriate to the
format provided when a base video format does not exactly match the format.

For example, given the following [sample frame (1 frame, 8 bit, 176x144, 4:4:4, progressive, YCbCr)](https://github.com/bbc/vc2-reference/files/4824053/qcif_ramps.zip),
and encoded as follows:

    EncodeHQ-CBR \
        -x 176 -y 144 -f 4:4:4 -n 1 -l 8 \
        -k LeGall -d 1 -a 1 -u 1 -s $((176*144*3*1)) \
        qcif_ramps.raw out.vc2

The output bitstream uses base video format 0 (custom format) and fails to
override the clean area from 640x480+0+0, which in this case is larger than the
picture resolution and therefore non-conforming.

For larger input formats, the same problem occurs although here the clean area
may not cover the whole frame which arguably is not a sensible default.

**Comment by GalenReich** [comment]
This code snippet no longer produces the error as #33 causes base video format 2 to be selected, which circumvents the error. However, the underlying error is still present.
