### ISSUE TITLE
Interested in status of this project

### ISSUE THREAD

**Issue by boxerab** [bbc/vc2-reference#2]
Is this codec under active development?  I am interested in getting involved.

**Comment by jamesba** [comment]
This repository contains the reference encoder and decoder. They're designed to produce correct bit streams according to the standard, but aren't designed for high performance, and we don't think that modifying these into a high performance implementation would work very well (but see below).

We're not actively adding new features to them right at the moment, but we are making bug fixes when we spot the need. They're intended as examples of how the VC-2 standard works more than as code that will actually be useful in real situations, but if you do find them useful then that's great too.

If you want to fork this code you are more than welcome to do so, and if you want to submit back any changes that you have made we're very happy to accept bug fixes. New features might be accepted depending on what they are.


We've also developed a second implementation of VC-2 HQ profile with much better performance designed for actual use as an encoder and decoder library (which we've been using internally); We're currently waiting for the final clearance to release it, which we expect to get fairly soon.

**Comment by boxerab** [comment]
Great, thanks for the update, James.  Looking forward to the release of the high performance version.

I've spent the last year and a half tinkering with an OpenCL implementation of JPEG 2000, so it would be interesting to try applying some of this knowledge to VC2.
