### ISSUE TITLE
Run with minimal commandline arguments

### ISSUE THREAD

**Issue by GalenReich** [bbc/vc2-reference#49]
It would be nice if a user could specify a minimum number of commandline arguments and get sensible output.

Arguments that specify the input format are required (width, height, colour format).

But current required arguments such as waveletDepth, hSlice, vSlice, mode, kernel, could be selected automatically or have sensible defaults.

**Comment by GalenReich** [comment]
Closing as not a desirable feature after discussion with @mossblaser

**Comment by mossblaser** [comment]
For posterity, it would be worth noting that the reason for not automating away these values is that what makes a sensible default will vary from application to application. For example, the choice of kernel and transform depth must be chosen carefully to balance compression performance and implementation size.
